[package]
name = "decoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.21", features = ["derive"] }
protobuf = "=3.2.0"
protobuf-json-mapping = "=3.2.0"
revm-primitives = "=1.1.2"
rand = "0.8.5"
reth-blockchain-tree = { git = "https://github.com/paradigmxyz/reth", version = "=0.1.0-alpha.4", tag = "v0.1.0-alpha.4" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", version = "=0.1.0-alpha.4", tag = "v0.1.0-alpha.4" }
thiserror = "1.0.44"
serde_json = "1.0.104"
serde = { version = "1.0.180", features = ["derive"] }
ethportal-api = "0.2.2"
zstd = "0.13.0"
# ethportal-api = { git = "https://github.com/ethereum/trin.git", version = "0.2.2" } 

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "decoder"
harness = false
