name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: build & test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      
      - name: Install Rustfmt
        run: rustup component add rustfmt
      - name: Check code formatting
        run: cargo fmt -- --check

      - name: Install Protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install Clippy
        run: rustup component add clippy
      - name: Run Clippy
        run: cargo clippy 


      - run: cargo build --verbose
      - run: cargo test --verbose